[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'out'
libs = ['lib']
evm_version = "paris"
solc_version = "0.8.20"
fork_block_number = 38400000
remappings = [
    'src/=contracts/src/',
    'pancake-v3-periphery/=lib/pancake-v3-contracts/projects/v3-periphery/contracts/',
    'pancake-v3-core/=lib/pancake-v3-contracts/projects/v3-core/contracts/',
    'aerodrome-v2/=lib/aerodrome-v2/contracts/'
]

[rpc_endpoints]
mainnet = "https://base-mainnet.g.alchemy.com/v2/z0-B5SXVWQSfl0XY9KLWa7kLRc7sl44p"

[profile.mainnet]
src = 'contracts/src'
test = 'contracts/test'
out = 'out'
libs = ['lib']

[dependencies]
"@openzeppelin/contracts" = "^5.0.1"

[profile.aerodrome]
solc_version = "0.8.19"
